version: '3.5'

network:
  influxdb-telegraf-net:
    driver: bridge

services: 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - 'env.influxdb'
    volumes:
     # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /datadrive/influxdb/:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
     - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#        - "3000:3000"
#     env_file:
#       - 'env.grafana'
#     user: "1000"
#     links:
#       - influxdb
#     volumes:
#       # Data persistency
#       # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
#     - /datadrive/grafana/:/var/lib/grafana
