version: '3.7'
services:

  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /datadrive/influxdb:/var/lib/influxdb:rw
    ports:
      - "8086:8086"

  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      -  /datadrive/influxdb:/var/lib/influxdb:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE: "Influxdb-setup"
      - DOCKER_INFLUXDB_INIT_USERNAME: "ezladmin"
      - DOCKER_INFLUXDB_INIT_PASSWORD: "P@ssw0rd123!"
      - DOCKER_INFLUXDB_INIT_ORG:  "ezlink"
      - DOCKER_INFLUXDB_INIT_BUCKET: /datadrive/influxdb/data_bucket/
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "abcdef"
      - INFLUXD_TLS_CERT: /etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY: /etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    depends_on:
      - influxdb

  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - ./influxv2.env
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG: "Influxdb-setup"
      - DOCKER_INFLUXDB_INIT_BUCKET: "/datadrive/influxdb/data_bucket/"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "abcdef" 
    depends_on:
      - influxdb_cli
volumes:
  influxdb:
